services:
  - type: web
    name: smart-home-dashboard
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0